spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3050/springDemoDB?allowPublicKeyRetrieval=true&useSSL=false&useTimezone=true&serverTimezone=UTC
    username: root
    password: 1010
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    show-sql: false